Repository yiisoft/active-record, pull requests merged in 2023-12, with the labels that each got.

#273 implement the interface ArrayableInterface for BaseActiveRecord
  composer.json
  src/ActiveRecordInterface.php
  src/BaseActiveRecord.php
  src/BaseActiveRecordTrait.php
  tests/ActiveRecordTest.php
  tests/Stubs/ActiveRecord/CustomerForArrayable.php
Labels: status:code review

#274 Fix setting value for an attribute when AR class has get method for the attribute
  src/BaseActiveRecordTrait.php
  tests/Stubs/ActiveRecord/Customer.php
Labels: type:bug

#277 Test `BaseActiveRecord::getOldAttribute()` after insert and update
  tests/ActiveQueryTest.php
Labels: type:test
